version: '3.7'

services:
  3at-nest-postgres:
    container_name: 3at-nest-postgres
    build: ./docker/postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  3at-nest-api:
    container_name: 3at-nest-api
    build: ./api
    depends_on:
      - 3at-nest-postgres
    ports:
      - "3000:3000"

  keycloak-dev:
    build: ./docker/keycloak
    container_name: keycloak-dev
    command: "-b 0.0.0.0 -Djboss.http.port=8180"
    ports:
      - "8180:8180"
    restart: unless-stopped
    ulimits:
      nproc: 60000
      nofile:
        soft: 32000
        hard: 40000
    env_file:
      - keycloak.env