name: 'CI on Merge to Main'

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  ci:
    name: 'Merge to main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Install dependencies'
        working-directory: .
        run: npm ci

      - name: 'Run Lint'
        working-directory: .
        run: npm run lint

      - name: 'Build'
        working-directory: .
        run: npm run build

      - name: 'Start the docker containers'
        run: |
          docker-compose -f ./docker-compose.yml up -d 3at-postgres

      - name: 'Unit Tests'
        working-directory: .
        run: npm run test

      - name: 'E2E tests'
        env:
          POSTGRES_HOST: 3at-nest-postgres  # Set the environment variable
        working-directory: .
        run: npm run test:e2e
